### ISSUE TITLE
Implement `zip()` operator

### ISSUE THREAD

**Issue by tetsuharuohzeki** [option-t/option-t#1337]
https://doc.rust-lang.org/std/option/enum.Option.html#method.zip

## TODO

- [ ] Implement `zip()` operator for `Maybe`
- [ ] Implement `zip()` operator for `Nullable`
- [ ] Implement `zip()` operator for `Undefinable`
- [x] #1601

**Comment by tetsuharuohzeki** [comment]
Implemented by https://github.com/option-t/option-t/pull/1798
