### ISSUE TITLE
Implement `zip_with()`

### ISSUE THREAD

**Issue by tetsuharuohzeki** [option-t/option-t#1338]
https://doc.rust-lang.org/std/option/enum.Option.html#method.zip_with

## TODO

- [ ] Implement `zip_with()` operator for `Maybe`
- [ ] Implement `zip_with()` operator for `Nullable`
- [ ] Implement `zip_with()` operator for `Undefinable`
- [x] #1546

**Comment by tetsuharuohzeki** [comment]
Done by #1800
