### ISSUE TITLE
Enable GitHub's merge queue

### ISSUE THREAD

**Issue by tetsuharuohzeki** [option-t/option-t#1912]
```[tasklist]
### Tasks
- [x] Enable Merge Queue from the branch protection.
- [x] https://github.com/option-t/option-t/pull/1908
- [x] https://github.com/option-t/option-t/pull/1913
- [x] Set "Require branches to be up to date before merging"
- [x] https://github.com/option-t/option-t/pull/1914
- [x] https://github.com/option-t/option-t/pull/1915
```

**Comment by tetsuharuohzeki** [comment]
We also set "Require branches to be up to date before merging" in branch protection to make the merge queue works well

**Comment by tetsuharuohzeki** [comment]
I disable merge queue. I seem it was not suite solution for our scalability. For the future, we should try it again.

**Comment by tetsuharuohzeki** [comment]
I enabled this again.
