### ISSUE TITLE
[meta] Export more items from `option-t/<TypeName>/namespace`

### ISSUE THREAD

**Issue by tetsuharuohzeki** [option-t/option-t#2024]
This tracks items that are not exported currently.

```[tasklist]
### Tasks
- [ ] https://github.com/option-t/option-t/issues/2025
- [ ] https://github.com/option-t/option-t/issues/2026
- [ ] https://github.com/option-t/option-t/issues/2027
- [ ] https://github.com/option-t/option-t/issues/2028
- [ ] https://github.com/option-t/option-t/issues/2029
```
