### ISSUE TITLE
[meta] Export more items from `option-t/PlainResult/namespace`

### ISSUE THREAD

**Issue by tetsuharuohzeki** [option-t/option-t#2025]
```[tasklist]
### Tasks
- [x] Result
- [ ] https://github.com/option-t/option-t/issues/2063
- [x] andThen
- [x] andThenAsync
- [ ] https://github.com/option-t/option-t/issues/2064
- [ ] https://github.com/option-t/option-t/issues/2065
- [ ] https://github.com/option-t/option-t/issues/2066
- [x] expect
- [x] flatten
- [ ] https://github.com/option-t/option-t/issues/2046
- [x] inspect
- [x] map
- [x] mapAsync
- [x] mapErr
- [x] mapErrAsync
- [x] mapOr
- [x] mapOrAsync
- [x] mapOrElse
- [x] mapOrElseAsync
- [ ] https://github.com/option-t/option-t/issues/2067
- [x] orElse
- [x] orElseAsync
- [x] toNullable
- [ ] https://github.com/option-t/option-t/issues/2062
- [x] toUndefinable
- [x] transpose
- [ ] https://github.com/option-t/option-t/issues/2048
- [ ] https://github.com/option-t/option-t/issues/2047
- [x] unwrap
- [x] unwrapOr
- [x] unwrapOrElse
- [x] unwrapOrElseAsync
- [ ] https://github.com/option-t/option-t/issues/2068
```
