### ISSUE TITLE
[meta] Export more items from `option-t/PlainOption/namespace`

### ISSUE THREAD

**Issue by tetsuharuohzeki** [option-t/option-t#2026]
```[tasklist]
### Tasks
- [x] Option
- [ ] https://github.com/option-t/option-t/issues/2049
- [x] andThen
- [x] andThenAsync
- [ ] https://github.com/option-t/option-t/issues/2038
- [ ] https://github.com/option-t/option-t/issues/2039
- [ ] https://github.com/option-t/option-t/issues/2050
- [x] expect
- [x] filter
- [x] flatten
- [x] inspect
- [x] map
- [x] mapAsync
- [x] mapOr
- [x] mapOrAsync
- [x] mapOrElse
- [x] mapOrElseAsync
- [x] okOr
- [x] okOrElse
- [ ] https://github.com/option-t/option-t/issues/2051
- [x] orElse
- [x] orElseAsync
- [ ] https://github.com/option-t/option-t/issues/2036
- [ ] https://github.com/option-t/option-t/issues/2040
- [x] transpose
- [x] unwrap
- [x] unwrapOr
- [x] unwrapOrElse
- [x] unwrapOrElseAsync
- [ ] https://github.com/option-t/option-t/issues/2052
```
