### ISSUE TITLE
[meta] Export more items from `option-t/PlainResult`

### ISSUE THREAD

**Issue by tetsuharuohzeki** [option-t/option-t#2030]
```[tasklist]
### Tasks
- [x] Result
- [ ] https://github.com/option-t/option-t/issues/2117
- [x] andThen
- [x] andThenAsync
- [ ] https://github.com/option-t/option-t/issues/2118
- [ ] https://github.com/option-t/option-t/issues/2119
- [ ] https://github.com/option-t/option-t/issues/2120
- [x] expect
- [x] flatten
- [ ] https://github.com/option-t/option-t/issues/2116
- [x] inspect
- [x] map
- [x] mapAsync
- [x] mapErr
- [x] mapErrAsync
- [x] mapOr
- [x] mapOrAsync
- [x] mapOrElse
- [x] mapOrElseAsync
- [ ] https://github.com/option-t/option-t/issues/2112
- [x] orElse
- [x] orElseAsync
- [ ] https://github.com/option-t/option-t/issues/2113
- [ ] https://github.com/option-t/option-t/issues/2114
- [ ] https://github.com/option-t/option-t/issues/2115
- [x] transpose
- [ ] https://github.com/option-t/option-t/issues/2111
- [ ] https://github.com/option-t/option-t/issues/2110
- [x] unwrap
- [x] unwrapOr
- [x] unwrapOrElse
- [x] unwrapOrElseAsync
- [ ] https://github.com/option-t/option-t/issues/2109
```
