### ISSUE TITLE
[meta] Export more items from `option-t/PlainOption`

### ISSUE THREAD

**Issue by tetsuharuohzeki** [option-t/option-t#2031]
```[tasklist]
### Tasks
- [x] Option
- [ ] https://github.com/option-t/option-t/issues/2099
- [x] andThen
- [x] andThenAsync
- [ ] https://github.com/option-t/option-t/issues/2100
- [ ] https://github.com/option-t/option-t/issues/2101
- [ ] https://github.com/option-t/option-t/issues/2102
- [x] expect
- [x] filter
- [x] flatten
- [x] inspect
- [x] map
- [x] mapAsync
- [x] mapOr
- [x] mapOrAsync
- [x] mapOrElse
- [x] mapOrElseAsync
- [ ] https://github.com/option-t/option-t/issues/2103
- [ ] https://github.com/option-t/option-t/issues/2104
- [ ] https://github.com/option-t/option-t/issues/2105
- [x] orElse
- [x] orElseAsync
- [ ] https://github.com/option-t/option-t/issues/2106
- [ ] https://github.com/option-t/option-t/issues/2107
- [x] transpose
- [x] unwrap
- [x] unwrapOr
- [x] unwrapOrElse
- [x] unwrapOrElseAsync
- [ ] https://github.com/option-t/option-t/issues/2108
```
