### ISSUE TITLE
Provide the way to "map `Err(unknown)` to `Err(Error)`" operator for `Result<T, E>` operation to make it easier to combinate with `tryCatchIntoResult`

### ISSUE THREAD

**Issue by tetsuharuohzeki** [option-t/option-t#2286]
## Sumamry

We want to a way to "map `Err(unknown)` to `Err(Error)`" operator for `Result<T, E>` operation to make it easier to combinate with `tryCatchIntoResult`

## Motivation

At first, as a _problem 1_, [`tryCatchIntoResult`](https://github.com/option-t/option-t/blob/801be2c8a2274451d12fc0af014ecfe1ad4222eb/packages/option-t/src/plain_result/try_catch.ts#L6-L22) produces `Result<T, unknown>`. We can make it into `Result<T, Error>` by `mapErr()` but it's a bit redundant.  User space can define a such operator function but it's also redundant. 

Indirectly, this mean that we don't recommend to use `tryCatchIntoResult` easily. This is just _our intended design_. We recommend (or require) to write a try-catch withing thinking about deeply what an inside throws. But it's a bit inconvenient.

Second, as a _problem 2_, [`tryCatchIntoResultWithEnsureError()`](https://github.com/option-t/option-t/blob/801be2c8a2274451d12fc0af014ecfe1ad4222eb/packages/option-t/src/plain_result/try_catch.ts#L24-L43) relax a the above _problem 1_. But its implementation depends on `e instanceof globalThis.Error` heavily. If a thrown object `e` is created by a constructor since another [realm](https://tc39.es/ecma262/2024/multipage/executable-code-and-execution-contexts.html#realm). This problem is similar to the motivation of [`Error.isError()` proposal](https://github.com/tc39/proposal-is-error). Times might resolve this by spreading `Error.isError()`. However, we cannot resolve this until then.

### Add the special operator as a variant of `mapErr()` like `function mapErrUnknownToError<T>(input: Result<T, unknown>): Result<T, Error>`.

See https://github.com/option-t/option-t/pull/2279

### Add a special variant to `tryCatchIntoResult()` as like `tryCatch` + `mapErr`

This increase a variants of `tryCatch`. It might make IntelliSense more complex
See https://github.com/option-t/option-t/pull/2287

## Depends on

```[tasklist]
### Tasks
- [ ] https://github.com/option-t/option-t/pull/2279
- [ ] https://github.com/option-t/option-t/pull/2287
- [ ] https://github.com/option-t/option-t/issues/2295
- [ ] https://github.com/option-t/option-t/issues/2296
- [ ] https://github.com/option-t/option-t/pull/2307
- [ ] https://github.com/option-t/option-t/pull/2308
- [ ] https://github.com/option-t/option-t/pull/2312
```

**Comment by tetsuharuohzeki** [comment]
> ### Add the special operator as a variant of `mapErr()` like `function mapErrUnknownToError<T>(input: Result<T, unknown>): Result<T, Error>`.
> 
> See #2279

This would be a useful. But this is too generic approach to resolve our motivations.

**Comment by tetsuharuohzeki** [comment]
> Add a special variant to `tryCatchIntoResult()` as like `tryCatch` + `mapErr`

I seem this solution is more nice at this time.
Typical case to generate `Result<T, unknown>` is originated from enclosure a exist throw-exception style codebase to bridge it to `Result`. I think we should care only this case by this issue. 

The others can be solved by _mapErr_.
