### ISSUE TITLE
Implement `copied()`

### ISSUE THREAD

**Issue by tetsuharuohzeki** [option-t/option-t#376]
https://doc.rust-lang.org/nightly/std/option/enum.Option.html#method.copied

## TODO

- [ ] Implement `copied` operator for `Maybe`
- [ ] Implement `copied` operator for `Nullable`
- [ ] Implement `copied` operator for `Undefinable`
- [x] #1606
- [ ] Implement `copied` operator for `PlainResult`

**Comment by saneyuki** [comment]
To implement this, we should introduce `Copy` as the type bound.

```typescript
interface Copy {
    copy(): self;
}
```

However, in JavaScript semantics, it might be a bit strange to think about _copying_.
I hesitate to implement this...

**Comment by tetsuharuohzeki** [comment]
It's enough to use [`structuredClone`](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone) + `map()` instead.
