### ISSUE TITLE
Implement `contains`

### ISSUE THREAD

**Issue by tetsuharuohzeki** [option-t/option-t#733]
- https://doc.rust-lang.org/std/option/enum.Option.html#method.contains
- https://doc.rust-lang.org/std/result/enum.Result.html#method.contains
- https://doc.rust-lang.org/std/result/enum.Result.html#method.contains_err

## TODO

- [ ] Implement `contains` operator for `Maybe`
- [ ] Implement `contains` operator for `Nullable`
- [ ] Implement `contains` operator for `Undefinable`
- [x] #1604
- [ ] Implement `contains` operator for `PlainResult`

**Comment by tetsuharuohzeki** [comment]
Rust has dropped `contains`
https://github.com/rust-lang/rust/pull/108095

**Comment by riking** [comment]
It's now named "is_some_and".

**Comment by tetsuharuohzeki** [comment]
> It's now named "is_some_and".

It’s filed as https://github.com/option-t/option-t/issues/1336
